spring:
  datasource:
#    url: jdbc:sqlserver://localhost;user=sa;password=12345678;databaseName=SBODEMODE;
    url: jdbc:h2:mem:test
  jpa:
    generate-ddl: true

spring.jpa.show-sql: true
#spring.jpa.properties.hibernate.format_sql: true

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl